name: Build and Publish Docker Image "latest"

on:
  release:
    types: [published]
    
  workflow_dispatch:
    inputs:
      tag:
        description: The tag to publish
        required: true

jobs:
  build-and-push:
    # if: github.event.release.prerelease == false && github.event.release.draft == false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Get Repository Name
        run: echo REPOSITORY_NAME=${GITHUB_REPOSITORY#*\/} >> $GITHUB_ENV
      

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --debug
      
      - name: Build Docker image
        id: test-build
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          load: true
          tags: |
            ${{ env.REPOSITORY_NAME }}:latest
      
      - name: Test image
        run: |
            docker run --rm  ${{ steps.test-build.outputs.imageid }}  
