name: Trigger Workflow on Latest Release

on:
  release:
    types: [published]

jobs:
  trigger_on_latest:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Workflow
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github.everest-preview+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            --data '{"event_type": "release-latest"}' \
            "https://api.github.com/repos/${{ github.repository }}/dispatches"